services:

  fsm:

    build:
      context: .
      dockerfile: Dockerfile

    image: li9i/fsm-lo:latest

    container_name: fsm_lo_container

    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host

    environment:
      - DISPLAY=${DISPLAY}

    user: ${USERNAME:-user_fsm}
