# Node parameters
scan_topic: '/base_scan'
initial_pose_topic: "/amcl_pose"
pose_estimate_topic: "/fsm_lidom/pose_estimate"
path_estimate_topic: "/fsm_lidom/path_estimate"
size_scan: 360

# Frames' parameters (The current pose is also published in the form of a
# transform [map_frame -> lidom_frame]---the sensor's current frame with
# respect to the map frame)
map_frame: '/map'
lidom_frame: '/lidom'

# FSM parameters
min_magnification_size: 0
max_magnification_size: 3
num_iterations: 2
xy_bound: 0.2
t_bound: 0.786
max_counter: 200
max_recoveries: 10
